// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateLanguage(arg1:string,arg2:string):Promise<void>;

export function GetAllLanguages():Promise<Array<backend.Language>>;

export function GetLanguageByID(arg1:number):Promise<backend.Language>;

export function UpdateLanguage(arg1:number,arg2:string):Promise<void>;
