// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateLanguage(arg1, arg2) {
  return window['go']['backend']['Language']['CreateLanguage'](arg1, arg2);
}

export function GetAllLanguages() {
  return window['go']['backend']['Language']['GetAllLanguages']();
}

export function GetLanguageByID(arg1) {
  return window['go']['backend']['Language']['GetLanguageByID'](arg1);
}

export function UpdateLanguage(arg1, arg2) {
  return window['go']['backend']['Language']['UpdateLanguage'](arg1, arg2);
}
