// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddToQueue(arg1:Array<backend.AddToQueueRequest>):Promise<void>;

export function DeleteFromQueue(arg1:number):Promise<void>;

export function ListQueue(arg1:string,arg2:backend.Pagination):Promise<backend.MovieQueueResponse>;
