// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['backend']['MovieQueue']['AddToQueue'](arg1);
}

export function DeleteFromQueue(arg1) {
  return window['go']['backend']['MovieQueue']['DeleteFromQueue'](arg1);
}

export function ListQueue(arg1, arg2) {
  return window['go']['backend']['MovieQueue']['ListQueue'](arg1, arg2);
}
