// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMovie(arg1, arg2, arg3) {
  return window['go']['backend']['Movie']['CreateMovie'](arg1, arg2, arg3);
}

export function GetMovieByID(arg1) {
  return window['go']['backend']['Movie']['GetMovieByID'](arg1);
}
