// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenAIKey() {
  return window['go']['backend']['Setting']['GetOpenAIKey']();
}

export function SaveOpenAIKey(arg1) {
  return window['go']['backend']['Setting']['SaveOpenAIKey'](arg1);
}
