// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSubtitlesByMovieID(arg1) {
  return window['go']['backend']['Subtitle']['GetSubtitlesByMovieID'](arg1);
}

export function UpdateSubtitle(arg1) {
  return window['go']['backend']['Subtitle']['UpdateSubtitle'](arg1);
}

export function UploadSRTFile(arg1, arg2) {
  return window['go']['backend']['Subtitle']['UploadSRTFile'](arg1, arg2);
}
