// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetSubtitlesByMovieID(arg1:number):Promise<Array<backend.Subtitle>>;

export function UpdateSubtitle(arg1:backend.Subtitle):Promise<void>;
