// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSubtitle(arg1, arg2) {
  return window['go']['backend']['Subtitle']['ExportSubtitle'](arg1, arg2);
}

export function GetSubtitlesByMovieID(arg1, arg2) {
  return window['go']['backend']['Subtitle']['GetSubtitlesByMovieID'](arg1, arg2);
}

export function ImportFromSRTFile(arg1, arg2) {
  return window['go']['backend']['Subtitle']['ImportFromSRTFile'](arg1, arg2);
}

export function TranslateSubtitles(arg1, arg2, arg3) {
  return window['go']['backend']['Subtitle']['TranslateSubtitles'](arg1, arg2, arg3);
}

export function UpdateSubtitle(arg1) {
  return window['go']['backend']['Subtitle']['UpdateSubtitle'](arg1);
}
